### ISSUE TITLE
VS2019 (RTM), 'references are missing'

### ISSUE THREAD

**Issue by oddbear** [renestein/ConfigureAwaitEnforcer#2]
Hi, I love this plugin, but I cannot install it (version 1.1.2.0) in VS2019 (RTM version 16.0.0).
The install log says 'references are missing':
```
04/04/2019 17:19:15 - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Desktop SDK\extension.vsixmanifest'
04/04/2019 17:19:15 - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\SDK ARM Additions\extension.vsixmanifest'
04/04/2019 17:19:15 - Found 'C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\Microsoft\Windows Kits\10\Windows Store SDK\extension.vsixmanifest'
04/04/2019 17:19:16 - Skipping 'C:\Users\oddbj\AppData\Local\Microsoft SDKs' as it doesn't exist
04/04/2019 17:19:16 - Beginning to install extension to Microsoft Visual Studio Enterprise 2019...
04/04/2019 17:19:17 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.Roslyn.LanguageServices (Microsoft.VisualStudio.Component.Roslyn.LanguageServices)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsCompPkg, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

Edit:
It's the 'Visual Studio Extension' (not the NuGet install)

**Comment by renestein** [comment]
Hi, thanks for the reporting. I am aware of this problem. Unfortunately, it appears that the cause of the missing reference is the omission of the required dependency in the visual studio installation.
E. g. see the following similar issue.

https://github.com/Microsoft/RoslynClrHeapAllocationAnalyzer/issues/68

I will investigate further and I will try to workaround this issue.

**Comment by renestein** [comment]
Even new vsix  that is created from the default extensibility template fail.
[Error dialog](https://snag.gy/JEYnm6.jpg)

**Comment by renestein** [comment]
@oddbear Please try the version 1.1.1.3 (available on the VS marketplace) and let me know the result.

**Comment by oddbear** [comment]
It seems to work perfect, thanks. :)

And thanks for the possibility to set diagnostics severity (I just saw that now).

**Comment by renestein** [comment]
@oddbear  Thanks for your kind words. Yes, the setting of the diagnostics severity is supported from the version 1.1.0.0.
